### ISSUE TITLE
Adding 11th mysql machine makes pmm-server unusable

### ISSUE THREAD

**Issue by hydrosine** [percona/pmm-server#10]
Adding up to 10 nodes works perfectly.
When adding the 11th the whole grafana/prometheus part dies.

Grafana shows no new data being added for any node (also the ones that worked before)

What i can find so far in the logging is that orchestrator.log started showing only the following log:
2016/12/01 16:19:05 statement.go:27: invalid connection
for every minute this repeats for the amount of monitoring nodes we have active.

before adding the 11th node this logline appears only periodically, but after the 11th node this is the only logline which remains.

Any clue on how to get the docker instance to work with more than ten nodes? What can I tune.
Only option for now is recreating the docker instance and re-attaching up to ten nodes with pmm-admin repair.

**Comment by hydrosine** [comment]
Fixed it by adding more memory to prometheus with `-e METRICS_MEMORY=1048576` in the docker run command

**Comment by roman-vynar** [comment]
Yes, you are correct, this is what I wanted to suggest.
