### ISSUE TITLE
Nginx Listen property

### ISSUE THREAD

**Issue by pedropilla** [percona/pmm-server#12]
Can you please provide an environment variable to set "listen *:80"?

**Comment by roman-vynar** [comment]
What's the problem? This is inside the container anyway. Also I cannot guarantee that other ports will work so smooth as non-80 due to rewrites and proxy passes.

**Comment by pedropilla** [comment]
The problem is not the port, but the IP that he binds, when you use host network stack he bind's all address, and when you have multiple IP's and containeir's running in the same host and all working in same port this change is necessary.

**Comment by roman-vynar** [comment]
There is no reason to run container with `--net=host`.

**Comment by pedropilla** [comment]
What? I think this option is mine considering that you don't know my infra. Anywhay, thanks for your attention and for nothing, I'll keep doing my Dockerfile!

**Comment by roman-vynar** [comment]
I was trying to understand what's the reason of running with `--net=host` as we do not mention this in the instructions. May be you have the reason for this but I try to understand the problem.
You are welcome to maintain your own Dockerfile.
