### ISSUE TITLE
No data in Grafana

### ISSUE THREAD

**Issue by JoyceBabu** [percona/pmm-server#4]
I have installed PMM as per the installation instructions. I have also configured the pmm-client, and QAN is showing my query details. But my Grafana / Prometheus dashboards are not displaying the monitored client stats.

**Comment by JoyceBabu** [comment]
The exporter service ports were not accessible from the host server. Sorry.

**Comment by roman-vynar** [comment]
Thanks. In the next 1.0.2 version, there will be a command to check the connectivity `pmm-admin check-networks`.
