### ISSUE TITLE
Orchestrator login / password

### ISSUE THREAD

**Issue by alekseyp** [percona/pmm-server#8]
To be able to change default user/passwd for Orchestrator's MySQLTopology, should we pass some of the variables as parameters when we start container? 
Or we can consider mounting our own /etc/orchestrator.conf.json or perhaps keeping it inside data volume?

**Comment by roman-vynar** [comment]
Yes, here is how https://www.percona.com/doc/percona-monitoring-and-management/using.html#orchestrator

**Comment by alekseyp** [comment]
👍 not sure how come i missed it @ entrypoint...
thanks!
